FiratOBS/MVC_web_UI/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Business;
using Entities;
using MVC_web_UI.Models;
using DataAccess;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace MVC_web_UI.Controllers
{
    public class StudentController : Controller
    {
        private readonly FirebaseDB _database = new FirebaseDB();
        private readonly Program _program = new Program();

        [HttpGet]
        public IActionResult StudentMain(Student student) // Öğrenci Giriş Ekranı 
        {
            Academician academician = _database.FindAcademician(student.CounselorMail);

            StudentModel model = new StudentModel()
            {
                Student = student,
                AcademicianName = academician.FirstName,
                AcademicianSurname = academician.LastName
            };

            string data = JsonSerializer.Serialize(model);
            TempData["studentModel"] = data;

            return View(model);
        }

        [HttpGet]
        public IActionResult AcademicCalendar() // Akademik Takvim
        {
            return View();
        }

        [HttpGet]
        public IActionResult ConsultantInformation() // Danışman Bilgileri
        {
            StudentModel studentModel = DeserializeModel();

            return View(studentModel);
        }

        [HttpGet]
        public IActionResult ReceivedLessons() // Alınan  Dersler
        {
            StudentModel studentModel = DeserializeModel();
            Student student = _database.FindStudents(studentModel.Student.Number);

            ReceivedLessonsModel model = new ReceivedLessonsModel()
            {
                ReceivedLessonsCode = student.ReceivedLessons,
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult ReceivedLessons(int selectPeriod)
        {
            StudentModel studentModel = DeserializeModel();
            Student student = _database.FindStudents(studentModel.Student.Number);
            PeriodListing periodListing = new PeriodListing(student.ReceivedLessons);
            
            ReceivedLessonsModel model = new ReceivedLessonsModel()
            {
                ReceivedLessonsCode = student.ReceivedLessons,
                Periods = periodListing.GetPeriods(selectPeriod),
                ReceivedLessons = _database.GetLessons(periodListing.GetPeriods(selectPeriod)),
                Selectperiod = periodListing.GetPeriodsName(selectPeriod)
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult ExamSchedule() // Sınav Takvimi
        {
            return View();
        }

        [HttpGet]
        public IActionResult InternshipInformation() // Staj Bilgileri
        {
            return View();
        }

        [HttpGet]
        public IActionResult LessonEnrollment() // Ders Kaydı
        {
            StudentModel studentModel = DeserializeModel();
            Student student = _database.FindStudents(studentModel.Student.Number);

            LessonEnrollmentProcess lessonEnrollmentProcess = new LessonEnrollmentProcess(_program.NextPeriod,_program.NextSeason);

            LessonEnrollmentModel model = new LessonEnrollmentModel()
            {
                NetxPeriod = _program.NextPeriod,
                NextSeason = _program.NextSeason,
                LessonsToBeLearned = lessonEnrollmentProcess.GetLessonsToBeLearned(student),
                RegisteredLessons = lessonEnrollmentProcess.GetRegisteredLessons(student),
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult LessonEnrollment(object obj) // Ders Kaydı
        {
            return View();
        }

        [HttpGet]
        public IActionResult NoteList() // Not Listesi
        {
            StudentModel studentModel = DeserializeModel();
            Student student = _database.FindStudents(studentModel.Student.Number);
            PeriodListing periodListing = new PeriodListing(student.ReceivedLessons);

            NoteListModel model = new NoteListModel()
            {
                Periods = periodListing.GetPeriods(), //periods (20-21 autumn, 20-21 spring)
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult NoteList(string selectPeriod) // Not Listesi
        {
            StudentModel studentModel = DeserializeModel();
            Student student = _database.FindStudents(studentModel.Student.Number);
            PeriodListing periodListing = new PeriodListing(student.ReceivedLessons);

            string period = periodListing.ConvertPeriodName(selectPeriod), season = periodListing.ConvertSeasonName(selectPeriod);

            List<string> receivedLessons = _database.GetReceivedLessons(student.Number, periodListing.PeriodsToInt(selectPeriod).ToString());
            List<string> lessonNames = _database.GetLessonName(receivedLessons);
            List<StudentNoteInfo> studentNoteInfos = _database.GetStudentNoteInfos(receivedLessons,period,season,student.Number);
            

            NoteListModel model = new NoteListModel()
            {
                Periods = periodListing.GetPeriods(), //periods (20-21 autumn, 20-21 spring)
                ReceivedLessons = receivedLessons,
                StudentNoteInfos = studentNoteInfos,
                LessonNames = lessonNames,
                Period = selectPeriod
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult TranscriptScript() // Transkript Senaryosu
        {
            return View();
        }

        [HttpGet]
        public IActionResult AbsenceStatus() // Devamsızlık Durumu
        {
            return View();
        }

        private StudentModel DeserializeModel()
        {
            string data = TempData["studentModel"].ToString();
            StudentModel studentModel = JsonSerializer.Deserialize<StudentModel>(data);
            return studentModel;
        }
    }
}

FiratOBS/MVC_web_UI/Views/Student/AbsenceStatus.cshtml
@{
    ViewData["Title"] = "Devamsızlık Durumu";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h1>AbsenceStatus (Devamsızlık Durumu)</h1>

FiratOBS/MVC_web_UI/Views/Student/AcademicCalendar.cshtml
@{
    ViewData["Title"] = "Akademik Takvim";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h1>AcademicCalendar(Akadamik Takvim)</h1>

FiratOBS/MVC_web_UI/Views/Student/ConsultantInformation.cshtml
@model StudentModel
@{
    ViewData["Title"] = "Danışman Bilgileri";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
    TempData["studentModel"] = TempData["studentModel"];
    ViewBag.mailExtentions = "@firat.edu.tr";
}

<div class="consultantInformation">
    
    <div class="header"><h2>Danışman Bilgileri</h2></div>

    <div class="card text-white mb-3 text-center">
        <div class="card-header">
            Danışman Bilgileri
        </div>
        <div class="card-body">
            <h5 class="card-title">@(Model.AcademicianName + " " + Model.AcademicianSurname)</h5>
            <p class="card-text">@(Model.Student.CounselorMail + ViewBag.mailExtentions.ToString())</p>
            <a href="https://mail.google.com/" class="btn btn-light d-grid">Danışmanla iletişime geç</a>
        </div>
    </div>

</div>

FiratOBS/MVC_web_UI/Views/Student/ExamSchedule.cshtml
@{
    ViewData["Title"] = "Sınav Takvimi";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h1>ExamSchedule (Sınav Takvimi)</h1>

FiratOBS/MVC_web_UI/Views/Student/InternshipInformation.cshtml
@{
    ViewData["Title"] = "Staj Bilgileri";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h1>InternshipInformation (Staj Bilgileri)</h1>

FiratOBS/MVC_web_UI/Views/Student/LessonEnrollment.cshtml
@model LessonEnrollmentModel
@{
    ViewData["Title"] = "Ders Kaydı";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
    TempData["studentModel"] = TempData["studentModel"];
}

<h1>LessonEnrollment (Ders Kaydı)</h1>

FiratOBS/MVC_web_UI/Views/Student/NoteList.cshtml
@model NoteListModel
@{
    ViewData["Title"] = "Not Listesi";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
    TempData["studentModel"] = TempData["studentModel"];
}

<div class= "noteList">

    @using (Html.BeginForm("NoteList", "Student", FormMethod.Post))
    {
    <select onchange="this.form.submit()" class="form-select" id="periodSelectNote" name="selectPeriod" aria-label="Default select example">

        <option selected disabled>Dönem Seçiniz</option>

        @for (int i = 0; i < Model.Periods.Count; i++)
        {
            <option>@Model.Periods[i]</option>
        }

    </select>
    }
    
    @if(Model.ReceivedLessons != null){

        <div class="header"><h2>@Model.Period</h2></div>

        <table class="table table-dark table-striped text-center">

            <thead>
                <tr>
                    <th scope="col">Ders Kodu</th>
                    <th scope="col">Ders Adı</th>
                    <th scope="col">Vize Notu</th>
                    <th scope="col">Final Notu</th>
                    <th scope="col">Bütünleme Notu</th>
                    <th scope="col">Ortalama</th>
                    <th scope="col">Harf Notu</th>
                    <th scope="col">Durum</th>
                </tr>
            </thead>
        
            <tbody>
            
            @for (int i = 0; i <Model.ReceivedLessons.Count; i++)
            {
                <tr>
                    <td scope="row">@Model.ReceivedLessons[i]</td>
                    <td scope="row">@Model.LessonNames[i]</td>
                    <td scope="row">@Model.StudentNoteInfos[i].MidtermExam</td>
                    <td scope="row">@Model.StudentNoteInfos[i].FinalExamination</td>

                    @if (Model.StudentNoteInfos[i].MakeupExam == 0)
                    {
                        <td scope="row">-</td>
                    }
                    else
                    {
                        <td scope="row">@Model.StudentNoteInfos[i].MakeupExam</td>
                    }

                    <td scope="row">@Model.StudentNoteInfos[i].Average</td>
                    <td scope="row">@Model.StudentNoteInfos[i].LetterGrade</td>
                    <td scope="row">@Model.StudentNoteInfos[i].Status</td>
                </tr>
            }

            </tbody>
        </table>
        
    }
</div>

FiratOBS/MVC_web_UI/Views/Student/ReceivedLessons.cshtml
@model ReceivedLessonsModel
@{
    ViewData["Title"] = "Alınan Dersler";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
    TempData["studentModel"] = TempData["studentModel"];


    List<string> periods = new List<string>(){"20-21","19-20","18-19","17-18"};
    List<string> season = new List<string>(){" Bahar Dönemi"," Güz Dönemi"};
    int periodIndex = 0;
}

<div class= "receivedLessons">

    @using (Html.BeginForm("ReceivedLessons", "Student", FormMethod.Post))
    {
        <select onchange="this.form.submit()" class="form-select" id="periodSelect" name="selectPeriod" aria-label="Default select example">

            <option disabled selected>Dönem Seçiniz</option>

            @for (int index = 0; index < Model.ReceivedLessonsCode.Count; index++)
            {
                if (Model.ReceivedLessonsCode.Count % 2 == 0)
                {
                    if (index % 2 == 0)
                    {
                        <option value=@index>@(periods[index: periodIndex] + season[0])</option> }
                    if (index % 2 != 0)
                    {
                        <option value=@index>@(periods[index: periodIndex] + season[1])</option>
                        periodIndex++;
                    }
                }

                else //if (Model.ReceivedLessonsCode.Count % 2 != 0)
                {
                    if (index == 1 || index % 2 != 0)
                        periodIndex++;

                    if (index % 2 == 0)
                    {
                        <option>@(periods[index: periodIndex] + season[1])</option> }
                    if (index % 2 != 0)
                    {
                        <option>@(periods[index: periodIndex] + season[0])</option>}
                    }
                }
        </select>
    }

    @if (Model.Periods != null)
    {

        <div class="header"><h2>@Model.Selectperiod</h2></div>

        <table class="table table-dark table-striped text-center">

            <thead>
                <tr>
                    <th scope="col">Ders Kodu</th>
                    <th scope="col">Ders Adı</th>
                    <th scope="col">Ders Tipi</th>
                    <th scope="col">Kredi</th>
                    <th scope="col">AKTS</th>
                    <th scope="col">Sınıf</th>
                    <th scope="col">Kota</th>
                </tr>
            </thead>
        
            <tbody>

                @foreach (var lesson in Model.ReceivedLessons)
                {
                    <tr>
                        <td scope="row">@lesson.LessonId</td>
                        <td scope="row">@lesson.LessonName</td>
                        <td scope="row">@lesson.LessonType</td>
                        <td scope="row">@lesson.Credit</td>
                        <td scope="row">@lesson.AKTS</td>
                        <td scope="row">@lesson.Class</td>
                        <td scope="row">@lesson.Quota</td>
                    </tr>
                }

            </tbody>
        </table>
        
    }
</div>

FiratOBS/MVC_web_UI/Views/Student/StudentMain.cshtml
@model StudentModel

@{
    ViewData["Title"] = "Öğrenci Ana Ekranı";
    ViewData["Mail Extension"] = "@firat.edu.tr";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


<div class="container pos-relaive">

    <div class="cards">
        <div class="card text-white bg-dark mb-3 col-3">
            <div class="card-header text-center"><h5>Öğrenim Bilgileri</h5></div>
            <div class="card-body text-center">
                <p class="card-text">
                    @Html.DisplayFor(model => model.Student.Faculty) <br>
                    @Html.DisplayFor(model => model.Student.Department) <br>
                    @Html.DisplayFor(model => model.Student.Class). Sınıf
                </p>
            </div>
        </div>

        <div class="card text-white bg-dark mb-3 col-3">
            <div class="card-header text-center"><h5>Danışman Bilgileri</h5></div>
            <div class="card-body text-center">
                <p class="card-text">
                    @Html.DisplayFor(model => model.AcademicianName)
                    @Html.DisplayFor(model => model.AcademicianSurname) <br>
                    @Html.DisplayFor(model => model.Student.CounselorMail)@ViewData["Mail Extension"]
                </p>
            </div>
        </div>

        <div class="card text-white bg-dark mb-3 col-3">
            <div class="card-header text-center"><h5>Transkript Bilgileri</h5></div>
            <div class="card-body text-center d-grid">
                <p class="card-text">AGNO : @Html.DisplayFor(model => model.Student.TranscriptNote)</p>
                <a href="#" class="btn btn-primary">İncele</a>
            </div>
        </div>
    </div>

</div>

FiratOBS/MVC_web_UI/Views/Student/TranscriptScript.cshtml
@{
    ViewData["Title"] = "Transkript Senaryosu";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h1>TranscriptScript (Transkript Senaryosu)</h1>